### ISSUE TITLE
Please make new release including PR #54

### ISSUE THREAD

**Issue by pgollangi** [pkg/term#55]
Current release has a bug building on macOS. 

```
##[error]../../../go/pkg/mod/github.com/pkg/term@v1.0.0/termios/ioctl.go:8:30: undefined: unix.SYS_IOCTL
```
This error was introduced with https://github.com/pkg/term/commit/1cd1864dfbfc5a77b108303511c30b6b08938de2#diff-55be90b78724feed63a53d4ea3212178 which was part of v1.0.0. 

This issue later resolved with https://github.com/pkg/term/commit/8dfd1b8a1225b475ec84ffe411b093d3d113ce9c#diff-55be90b78724feed63a53d4ea3212178 which is part of #54 

It would be very helpful to make a new release including this fix. Otherwise go modules catching v1.0.0 which failes on macOS.

**Comment by davecheney** [comment]
Done v1.1.0
